### PR TITLE
Upgrade protobuf to 34.1

### PR DESCRIPTION
**Pull request by 06393993**

### CODE REVIEW

**Comment by 06393993** [comment]
```
2026-05-15 15:24:48 PDT
(22:24:48) ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/com_google_protobuf/src/google/protobuf/BUILD.bazel:319:14: in proto_library rule @@com_google_protobuf//src/google/protobuf:descriptor_proto:
2026-05-15 15:24:48 PDT
Traceback (most recent call last):
2026-05-15 15:24:48 PDT
    File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/com_google_protobuf/bazel/private/proto_library_rule.bzl", line 89, column 27, in _proto_library_impl
2026-05-15 15:24:48 PDT
        proto_info = ProtoInfo(
2026-05-15 15:24:48 PDT
    File "/virtual_builtins_bzl/common/proto/proto_info.bzl", line 144, column 24, in ProtoInfo
2026-05-15 15:24:48 PDT
    File "/virtual_builtins_bzl/common/proto/proto_info.bzl", line 47, column 5, in _create_proto_info
2026-05-15 15:24:48 PDT
Error: _create_proto_info() got unexpected keyword arguments: option_deps, extension_declarations
```

It seems that 34.1 protobuf can't work with bazel 7.7.1, and that's official:

https://protobuf.dev/support/migration/#dropped-bazel-7-support.

What's our opinion on that?
